name: Release

on:  
  release:
    types: [prereleased, released, workflow_dispatch]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore dcs-dtc.sln

      - name: Build Solution
        run: |
          msbuild.exe dcs-dtc.sln /p:platform="Any CPU" /p:configuration="Release"

      - uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: dcs-dtc/bin/Release

      # Upload artifact as a release asset
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./dcs-dtc/bin/Release
